### ISSUE TITLE
KYC008 : adapter question

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/agir-back#18]
https://github.com/betagouv/agir-back/blob/4b5aca208914b03283289b50957f3f55ddf337ee/src/domain/kyc/catalogueQuestionsKYC.ts#L144

Reformuler ? Il semble que le texte ne soit pas le bon.

**Comment by WoWo79** [comment]
Bonjour et merci pour le pointeur !!
C'est corrigé ^^
