### ISSUE TITLE
Aides vélo : prolongation jusqu'en 2027

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/agir-back#19]
https://github.com/betagouv/agir-back/blob/4b5aca208914b03283289b50957f3f55ddf337ee/src/infrastructure/data/aidesVelo.json#L23

Le dispositif est reconduit pour plusieurs années https://www.economie.gouv.fr/particuliers/prime-velo-electrique

**Comment by WoWo79** [comment]
Merci pour le pointeur !
On a bien dans la todo de faire une passe sur l'ensemble du simultateur pour le mettre à jour
Pour info nous nous basons sur ce référentiel là : https://mesaidesvelo.fr/

**Comment by AntoineAugusti** [comment]
@mquandalle est partout !
