### ISSUE TITLE
Aides vélo : toujours éligible

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/agir-back#20]
![image](https://github.com/betagouv/agir-back/assets/295709/640c39fe-b686-4fba-b4bc-c7af03350cf8)

Les données de l'utilisateur permettent de renseigner "Revenu fiscal de référence : Plus de 28 178 €" pour la valeur la plus élevée.

On peut [obtenir une aide à l'achat pour un VAE](https://www.service-public.fr/particuliers/vosdroits/F36603/1_1_1?idFicheParent=F36828#1_1_1) si le RFR par part est <= 15 400 €, ce qui est toujours vrai avec les paramètres possibles actuellement.

**Comment by WoWo79** [comment]
En effet, ça n'a pas l'air d'influer sur les VAE, sur d'autres aides en revanche,
On va néanmoins vérifier tout celà
Merci !!
